name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.13.2

      - name: install Mocha and unit test packages
        run: |
          cd src;
          npm install -g mocha
          npm install

      - name: execute tests
        run: mocha src/test/convert.js

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          # Password or personal access token used to log against the Docker registry
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: src
          file: src/Dockerfile
          push: true
          tags: |
            eduardatsantanna/aula-conversao-temperatura:${{github.run_number}}
            eduardatsantanna/aula-conversao-temperatura:latest
